[project]
name = "tinder-gen-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-genai>=1.38.0",
    "streamlit>=1.49.1",
]
